# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: beeebe53d7be500b6245abfa5b319c2df12b16c42aa9552bd75bab8440a9177a118fe1e8d87e61b26d872da4e083481e24de79c07b5db992292c5ca5948130b5

test:
  secret_key_base: 873f412d353edcfc150c197a26aae8bd1cc524a531c648afcffd0e89952383b9d9247129b4d91844096a5d5d215078aff04598f41c2a0cb7fdce0b0ee542bb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
